version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 474668407017.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t jetson-container .
      - docker tag jetson-container-1:latest  474668407017.dkr.ecr.us-east-1.amazonaws.com/jetson-container-1:latest

  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push 474668407017.dkr.ecr.us-east-1.amazonaws.com/jetson-container-1:latest
