
services:
  
  camera:
    build: ./camera
    container_name: camera
    network_mode: "host"
    environment:
      - DISPLAY=$DISPLAY  # Enables GUI display
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix  # Share X11 socket for display
      

  object_detection:
    build: ./object_detection
    container_name: object_detection
    network_mode: "host"
    environment:
      - DISPLAY=$DISPLAY  # Enables GUI display if needed
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix  # Share X11 socket for display
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    
